# dbt_project.yml
# Example project-level configuration & metadata 


name: airbnb

profile: airbnb   # must match profile.yml target name

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  airbnb:
    +schema: raw

# Project level configurations
models:
  airbnb:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table






